export const SYMBOLS = ['01d', '02d', '03d', '04','05d', '06d', '07d', '08d', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20d', '21d', '22', '23', '24d', '25d', '26d', '27d', '28d', '29d', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40d', '41d', '42d', '43d', '44d', '45d', '46', '47', '48', '49', '50'];
export const paris = {
  "_id": 2988507,
  "name": "Paris",
  "alternate_names": [
    "baariis",
    "bahliz",
    "gorad paryzh",
    "lungsod ng paris",
    "lutece",
    "lutetia",
    "lutetia parisorum",
    "lutèce",
    "par",
    "pa-ri",
    "paarys",
    "palika",
    "paname",
    "pantruche",
    "paraeis",
    "paras",
    "pari",
    "paries",
    "parigge",
    "pariggi",
    "parighji",
    "parigi",
    "pariis",
    "pariisi",
    "pariizu",
    "pariižu",
    "parij",
    "parijs",
    "paris",
    "parisi",
    "parixe",
    "pariz",
    "parize",
    "parizh",
    "parizh osh",
    "parizh'",
    "parizo",
    "parizs",
    "pariž",
    "parys",
    "paryz",
    "paryzius",
    "paryż",
    "paryžius",
    "paräis",
    "parís",
    "paríž",
    "parîs",
    "parĩ",
    "parī",
    "parīze",
    "paříž",
    "páras",
    "párizs",
    "ville-lumiere",
    "ville-lumière",
    "ba li",
    "barys",
    "pairisa",
    "pali",
    "pari",
    "paris",
    "parys",
    "paryzh",
    "perisa",
    "pryz",
    "pyaris",
    "pyarisa",
    "pyrs",
    "παρίσι",
    "горад парыж",
    "париж",
    "париж ош",
    "парижь",
    "париз",
    "парис",
    "паріж",
    "փարիզ",
    "פאריז",
    "פריז",
    "باريس",
    "پارىژ",
    "پاريس",
    "پاریس",
    "پیرس",
    "ܦܐܪܝܣ",
    "पॅरिस",
    "पेरिस",
    "पैरिस",
    "প্যারিস",
    "ਪੈਰਿਸ",
    "પૅરિસ",
    "பாரிஸ்",
    "పారిస్",
    "ಪ್ಯಾರಿಸ್",
    "പാരിസ്",
    "ปารีส",
    "ཕ་རི།",
    "ပါရီမြို့",
    "პარიზი",
    "ፓሪስ",
    "ប៉ារីស",
    "パリ",
    "巴黎",
    "파리"
  ],
  "coordinates": [
    48.85341,
    2.3488
  ],
  "country_code": "FR",
  "population": 2138551,
  "elevation": 0
};
